# PersistentVolumeClaim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sabnzbd-server-config
  namespace: sabnzbd
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
---
# ConfigMap Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-server
  namespace: sabnzbd
  labels:
    app: sabnzbd
data:
  TZ: "America/Chicago"
  PUID: "0"
  PGID: "0"
---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd-server
  namespace: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      volumes:
      - name: server-config
        persistentVolumeClaim:
          claimName: pvc-sabnzbd-server-config
      containers:
      - name: sabnzbd-server
        image: linuxserver/sabnzbd:3.0.1
        volumeMounts:
          - name: server-config
            mountPath: /config
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        envFrom:
          - configMapRef:
              name: sabnzbd-server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9090
          name: https
          protocol: TCP
---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-server
  namespace: sabnzbd
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
    nodePort: 32011
  - port: 9090
    name: https
    protocol: TCP
    targetPort: 9090
    nodePort: 32012
  selector:
    app: sabnzbd
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---