---
# Namespace Configuration
apiVersion: v1
kind: Namespace
metadata:
  name: usenet
---
# PersistentVolume Configuration
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sabnzbd-config
  namespace: usenet
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.110.245
    path: "/mnt/pool2/kubernetes-data/sabnzbd/config"
---
# PersistentVolumeClaim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sabnzbd-config
  namespace: usenet
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# PersistentVolume Configuration
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sabnzbd-completed-downloads
  namespace: usenet
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.110.245
    path: "/mnt/pool2/kubernetes-data/sabnzbd/completed-downloads"
---
# PersistentVolumeClaim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sabnzbd-completed-downloads
  namespace: usenet
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# PersistentVolume Configuration
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sabnzbd-incomplete-downloads
  namespace: usenet
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.110.245
    path: "/mnt/pool2/kubernetes-data/sabnzbd/incomplete-downloads"
---
# PersistentVolumeClaim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sabnzbd-incomplete-downloads
  namespace: usenet
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-service
  namespace: usenet
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32111
  selector:
    app: sabnzbd
  sessionAffinity: None
  type: NodePort
---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd-deployment
  namespace: usenet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      volumes:
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: pvc-sabnzbd-config
      - name: sabnzbd-completed-downloads
        persistentVolumeClaim:
          claimName: pvc-sabnzbd-completed-downloads
      - name: sabnzbd-incomplete-downloads
        persistentVolumeClaim:
          claimName: pvc-sabnzbd-incomplete-downloads
      containers:
      - name: sabnzbd
        image: linuxserver/sabnzbd
        volumeMounts:
          - name: sabnzbd-config
            mountPath: /config
          - name: sabnzbd-completed-downloads
            mountPath: /downloads
          - name: sabnzbd-incomplete-downloads
            mountPath: /incomplete-downloads
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - containerPort: 6789
---