---
# ConfigMap Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-apc-ups-telegraf-config
  namespace: apc
  labels:
    app: apc-telegraf
data:
  telegraf-apc-ups.conf: |-
    # Telegraf Configuration

    [agent]
      interval = "10s"
      round_interval = true

    [[outputs.influxdb]]
        urls = ["http://influxdb.jittersolutions.com"]
        database = "apc"
        insecure_skip_verify = true
        #ssl_ca = "/usr/local/etc/telegraf.ca"
    
    ## INPUT CONFIGURATION
    ### Retrieves details via SNMP from APC Smart-UPS (SMT1500R2X180)
    ### Extra MIBs required:
    ### - https://download.schneider-electric.com/files?p_enDocType=Firmware+-+Released&p_Doc_Ref=APC_POWERNETMIB_432&p_File_Name=powernet432.mib

    [[inputs.snmp]]
      # List of agents to poll
      agents = [ "ups1dc1" ]
      # Polling interval
      interval = "60s"
      # Timeout for each SNMP query.
      timeout = "10s"
      # Number of retries to attempt within timeout.
      retries = 3
      # SNMP version
      version = 2
      # SNMP community string.
      community = "public"
      # Measurement name
      name = "snmp.UPS"
      ##
      ## System Details
      ##
      #  System name (hostname)
      [[inputs.snmp.field]]
        is_tag = true
        name = "upsBasicIdentName"
        oid = "PowerNet-MIB::upsBasicIdentName.0"
      #
---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-telegraf
  namespace: apc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apc-telegraf
  template:
    metadata:
      labels:
        app: apc-telegraf
    spec:
      volumes:
      - name: apc-ups-telegraf-config
        configMap:
          defaultMode: 0600
          name: cm-apc-ups-telegraf-config
      containers:
      - name: apc-telegraf
        image: telegraf:alpine
        command: ["/bin/sh", "-c"]
        args: [
          "wget 'https://download.schneider-electric.com/files?p_enDocType=Firmware+-+Released&p_Doc_Ref=APC_POWERNETMIB_432&p_File_Name=powernet432.mib' -O /usr/share/snmp/mibs/APC-SMARTUPS-MIB; telegraf",
        ]
        volumeMounts:
          - name: apc-ups-telegraf-config
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf-apc-ups.conf
            readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
---