---
# ConfigMap Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-apc-ups-telegraf-config
  namespace: apc
  labels:
    app: apc-telegraf
data:
  telegraf-apc-ups.conf: |-
    # Telegraf Configuration

    [agent]
      interval = "10s"
      round_interval = true

    [[outputs.influxdb]]
        urls = ["http://k8snode1dc1.jittersolutions.com:30030"]
        database = "apc-smartups"
        insecure_skip_verify = true
        #ssl_ca = "/usr/local/etc/telegraf.ca"
    
    ## INPUT CONFIGURATION
    ### Retrieves details via SNMP from APC Smart-UPS (SMT1500R2X180)
    ### Extra MIBs required:
    ### - https://download.schneider-electric.com/files?p_enDocType=Firmware+-+Released&p_Doc_Ref=APC_POWERNETMIB_432&p_File_Name=powernet432.mib

    [[inputs.snmp]]
      # List of agents to poll
      agents = [ "ups1dc1.domain.local" ]
      # Polling interval
      interval = "60s"
      # Timeout for each SNMP query.
      timeout = "10s"
      # Number of retries to attempt within timeout.
      retries = 3
      # SNMP version
      version = 2
      # SNMP community string.
      community = "public"
      # Measurement name
      name = "snmp.UPS"
      ##
      ## System Details
      ##
      #  System name (hostname)
        [[inputs.snmp.field]]
        is_tag = true
        name = "sysName"
        oid = "RFC1213-MIB::sysName.0"
      #  System vendor OID
      [[inputs.snmp.field]]
        name = "sysObjectID"
        oid = "RFC1213-MIB::sysObjectID.0"
      #  System description
      [[inputs.snmp.field]]
        name = "sysDescr"
        oid = "RFC1213-MIB::sysDescr.0"
      #  System contact
      [[inputs.snmp.field]]
        name = "sysContact"
        oid = "RFC1213-MIB::sysContact.0"
      #  System location
      [[inputs.snmp.field]]
        name = "sysLocation"
        oid = "RFC1213-MIB::sysLocation.0"
      #  System uptime
      [[inputs.snmp.field]]
        name = "sysUpTime"
        oid = "RFC1213-MIB::sysUpTime.0"
      [[inputs.snmp.field]]
        name = "upsBasicIdentModel"
        oid = "PowerNet-MIB::upsBasicIdentModel.0"
      [[inputs.snmp.field]]
        name = "upsBasicIdentName"
        oid = "PowerNet-MIB::upsBasicIdentName.0"
      [[inputs.snmp.field]]
        name = "upsAdvIdentFirmwareRevision"
        oid = "PowerNet-MIB::upsAdvIdentFirmwareRevision.0"
      [[inputs.snmp.field]]
        name = "upsAdvIdentDateOfManufacture"
        oid = "PowerNet-MIB::upsAdvIdentDateOfManufacture.0"
      [[inputs.snmp.field]]
        name = "upsAdvIdentSerialNumber"
        oid = "PowerNet-MIB::upsAdvIdentSerialNumber.0"
      [[inputs.snmp.field]]
        name = "upsAdvIdentSkuNumber"
        oid = "PowerNet-MIB::upsAdvIdentSkuNumber.0"
    ###########################################  
      [[inputs.snmp.field]]
        name = "upsBasicBatteryStatus"
        oid = "PowerNet-MIB::upsBasicBatteryStatus.0"
      [[inputs.snmp.field]]
        name = "upsBasicBatteryTimeOnBattery"
        oid = "PowerNet-MIB::upsBasicBatteryTimeOnBattery.0"
      [[inputs.snmp.field]]
        name = "upsBasicBatteryLastReplaceDate"
        oid = "PowerNet-MIB::upsBasicBatteryLastReplaceDate.0"
      [[inputs.snmp.field]]
        name = "upsAdvBatteryCapacity"
        oid = "PowerNet-MIB::upsAdvBatteryCapacity.0"
        [[inputs.snmp.field]]
        name = "upsAdvBatteryTemperature"
        oid = "PowerNet-MIB::upsAdvBatteryTemperature.0"
      [[inputs.snmp.field]]
        name = "upsAdvBatteryRunTimeRemaining"
        oid = "PowerNet-MIB::upsAdvBatteryRunTimeRemaining.0"
      [[inputs.snmp.field]]
        name = "upsAdvBatteryReplaceIndicator"
        oid = "PowerNet-MIB::upsAdvBatteryReplaceIndicator.0"
      [[inputs.snmp.field]]
        name = "upsAdvBatteryActualVoltage"
        oid = "PowerNet-MIB::upsAdvBatteryActualVoltage.0"
      [[inputs.snmp.field]]
        name = "upsAdvBatteryInternalSKU"
        oid = "PowerNet-MIB::upsAdvBatteryInternalSKU.0"
      [[inputs.snmp.field]]
        name = "upsAdvBatteryRecommendedReplaceDate"
        oid = "PowerNet-MIB::upsAdvBatteryRecommendedReplaceDate.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecBatteryCapacity"
        oid = "PowerNet-MIB::upsHighPrecBatteryCapacity.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecBatteryTemperature"
        oid = "PowerNet-MIB::upsHighPrecBatteryTemperature.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecBatteryActualVoltage"
        oid = "PowerNet-MIB::upsHighPrecBatteryActualVoltage.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecBattery.13"
        oid = "PowerNet-MIB::upsHighPrecBattery.13.0"
      [[inputs.snmp.field]]
        name = "upsBasicInputPhase"
        oid = "PowerNet-MIB::upsBasicInputPhase.0"
      [[inputs.snmp.field]]
        name = "upsAdvInputLineVoltage"
        oid = "PowerNet-MIB::upsAdvInputLineVoltage.0"
      [[inputs.snmp.field]]
        name = "upsAdvInputMaxLineVoltage"
        oid = "PowerNet-MIB::upsAdvInputMaxLineVoltage.0"
      [[inputs.snmp.field]]
        name = "upsAdvInputMinLineVoltage"
        oid = "PowerNet-MIB::upsAdvInputMinLineVoltage.0"
      [[inputs.snmp.field]]
        name = "upsAdvInputFrequency"
        oid = "PowerNet-MIB::upsAdvInputFrequency.0"
      [[inputs.snmp.field]]
        name = "upsAdvInputLineFailCause"
        oid = "PowerNet-MIB::upsAdvInputLineFailCause.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecInputLineVoltage"
        oid = "PowerNet-MIB::upsHighPrecInputLineVoltage.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecInputMaxLineVoltage"
        oid = "PowerNet-MIB::upsHighPrecInputMaxLineVoltage.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecInputMinLineVoltage"
        oid = "PowerNet-MIB::upsHighPrecInputMinLineVoltage.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecInputFrequency"
        oid = "PowerNet-MIB::upsHighPrecInputFrequency.0"
      [[inputs.snmp.field]]
        name = "upsBasicOutputStatus"
        oid = "PowerNet-MIB::upsBasicOutputStatus.0"
      [[inputs.snmp.field]]
        name = "upsBasicOutputPhase"
        oid = "PowerNet-MIB::upsBasicOutputPhase.0"
      [[inputs.snmp.field]]
        name = "upsAdvOutputVoltage"
        oid = "PowerNet-MIB::upsAdvOutputVoltage.0"
      [[inputs.snmp.field]]
        name = "upsAdvOutputFrequency"
        oid = "PowerNet-MIB::upsAdvOutputFrequency.0"
      [[inputs.snmp.field]]
        name = "upsAdvOutputLoad"
        oid = "PowerNet-MIB::upsAdvOutputLoad.0"
      [[inputs.snmp.field]]
        name = "upsAdvOutputCurrent"
        oid = "PowerNet-MIB::upsAdvOutputCurrent.0"
      [[inputs.snmp.field]]
        name = "upsAdvOutputActivePower"
        oid = "PowerNet-MIB::upsAdvOutputActivePower.0"
      [[inputs.snmp.field]]
        name = "upsAdvOutputApparentPower"
        oid = "PowerNet-MIB::upsAdvOutputApparentPower.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecOutputVoltage"
        oid = "PowerNet-MIB::upsHighPrecOutputVoltage.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecOutputFrequency"
        oid = "PowerNet-MIB::upsHighPrecOutputFrequency.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecOutputLoad"
        oid = "PowerNet-MIB::upsHighPrecOutputLoad.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecOutputCurrent"
        oid = "PowerNet-MIB::upsHighPrecOutputCurrent.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecOutputEfficiency"
        oid = "PowerNet-MIB::upsHighPrecOutputEfficiency.0"
      [[inputs.snmp.field]]
        name = "upsHighPrecOutputEnergyUsage"
        oid = "PowerNet-MIB::upsHighPrecOutputEnergyUsage.0"
      [[inputs.snmp.field]]
        name = "upsBasicConfigNumDevices"
        oid = "PowerNet-MIB::upsBasicConfigNumDevices.0"
---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-telegraf
  namespace: apc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apc-telegraf
  template:
    metadata:
      labels:
        app: apc-telegraf
    spec:
      volumes:
      - name: apc-ups-telegraf-config
        configMap:
          defaultMode: 0600
          name: cm-apc-ups-telegraf-config
      containers:
      - name: apc-telegraf
        image: telegraf:alpine
        command: ["/bin/sh", "-c"]
        args: [
          "wget 'https://download.schneider-electric.com/files?p_enDocType=Firmware+-+Released&p_Doc_Ref=APC_POWERNETMIB_432&p_File_Name=powernet432.mib' -O /usr/share/snmp/mibs/PowerNet-MIB; telegraf",
        ]
        volumeMounts:
          - name: apc-ups-telegraf-config
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf-apc-ups.conf
            readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
---