---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: traefik
  labels: 
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: containous/whoami
        ports: 
          - name: web
            containerPort: 80
      nodeSelector:
        hostname: k8snode2dc1.jittersolutions.com
---
kind: Service
apiVersion: v1
metadata:
  name: whoami
  namespace: traefik
spec:
#  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: web
  selector:
    app: whoami
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: whoami
  namespace: traefik
spec:
  entryPoints: 
    - web
  routes:
  - match: "Host(`k8snode2dc1.jittersolutions.com`)" 
    kind: Rule
    services:
    - name: whoami
      port: 80
---