---
# Deployment Configuration
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: traefik
  labels: 
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: containous/whoami
        ports: 
          - name: web
            containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# Service Configuration
kind: Service
apiVersion: v1
metadata:
  name: whoami
  namespace: traefik
spec:
  ports:
  - protocol: TCP
    port: 80
    name: web
  selector:
    app: whoami
---
# IngressRoute Configuration
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: whoami
  namespace: traefik
spec:
  entryPoints: 
    - web
  routes:
  - match: "Host(`k8snode2dc1.jittersolutions.com`)" 
    kind: Rule
    services:
    - name: whoami
      port: 80
---