---
# PersistentVolumeClaim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-unifi-controller-data
  namespace: unifi-controller
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# ConfigMap Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-controller
  namespace: unifi-controller
  labels:
    app: unifi-controller
data:
  TZ: "America/Chicago"
##########
---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller
  namespace: unifi-controller
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
    nodePort: 30100
  - port: 8443
    name: https
    protocol: TCP
    targetPort: 8443
  - port: 3478
    name: question1
    protocol: TCP
    targetPort: 3478
  - port: 10001
    name: question2
    protocol: TCP
    targetPort: 10001
  selector:
    app: unifi-controller
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      volumes:
      - name: unifi-controller-data
        persistentVolumeClaim:
          claimName: pvc-unifi-controller-data
      containers:
      - name: unifi-controller
        image: jacobalberty/unifi:stable
        volumeMounts:
          - name: unifi-controller-data
            mountPath: /unifi
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        envFrom:
          - configMapRef:
              name: unifi-controller
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        - containerPort: 3478
          name: dunno1
        - containerPort: 10001
          name: dunno2
---