---
# PersistentVolumeClaim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-certbot-etc-letsencrypt
  namespace: certbot
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
---
# PersistentVolumeClaim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-certbot-var-lib-letsencrypt
  namespace: certbot
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
# PersistentVolumeClaim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-certbot-var-log-letsencrypt
  namespace: certbot
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
# ConfigMap Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-certbot-cloudflare-config
  namespace: certbot
  labels:
    app: certbot
data:
  cloudflare.ini: |
    dns_cloudflare_email = ${DNS_CLOUDFLARE_EMAIL}
    dns_cloudflare_api_key ${DNS_CLOUDFLARE_API_KEY}
---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certbot
  namespace: certbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certbot
  template:
    metadata:
      labels:
        app: certbot
    spec:
      volumes:
      - name: certbot-etc-letsencrypt
        persistentVolumeClaim:
          claimName: pvc-certbot-etc-letsencrypt
      - name: certbot-var-lib-letsencrypt
        persistentVolumeClaim:
          claimName: pvc-certbot-var-lib-letsencrypt
      - name: certbot-var-log-letsencrypt
        persistentVolumeClaim:
          claimName: pvc-certbot-var-log-letsencrypt
      - name: certbot-cloudflare-config-volume
        configMap:
          defaultMode: 0600
          name: cm-certbot-cloudflare-config
      containers:
      - name: certbot
        image: certbot/dns-cloudflare:latest
        args: [
          "certonly",
          "--dns-cloudflare",
          "--dns-cloudflare-credentials", "/etc/cloudflare.ini",
          "-d", "jittersolutions.com",
        ]
        volumeMounts:
          - name: certbot-etc-letsencrypt
            mountPath: /etc/letsencrypt
          - name: certbot-var-lib-letsencrypt
            mountPath: /var/lib/letsencrypt
          - name: certbot-var-log-letsencrypt
            mountPath: /var/log/letsencrypt
          - name: certbot-cloudflare-config-volume
            mountPath: /etc/cloudflare.ini
            subPath: cloudflare.ini
            readOnly: false
        env:
        - name: DNS_CLOUDFLARE_EMAIL
          valueFrom:
            secretKeyRef:
              name: certbot
              key: dns-cloudflare-email
        - name: DNS_CLOUDFLARE_API_KEY
          valueFrom:
            secretKeyRef:
              name: certbot
              key: dns-cloudflare-api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsUser: 0
      restartPolicy: Never
---