---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: jenkins-server-ingressroute
  namespace: jenkins
spec:
  entryPoints: 
    - web
  routes:
  - kind: Rule
    match: "Host(`k8snod1dc1.jittersolutions.com`) && Path(`/jenkins`)"
    priority: 10
    service: jenkins
  services:
    jenkins:
      loadBalancer:
        servers:
          - url: "https://www.google.com"
---