---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: jenkins-server-ingressroute
  namespace: jenkins
spec:
  entryPoints: 
    - web
  routes:
  - kind: Rule
    match: "Path(`/jenkins`)"
    priority: 10
    services:
    - name: jenkins-server
      port: 8080
      passHostHeader: true
      responseForwarding:
        flushInterval: 100ms
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: jenkins-server-ingressroutez
  namespace: jenkins
spec:
  entryPoints: 
    - web
  routes:
  - kind: Rule
    match: "Path(`/login?from=%2Fjenkins`)"
    priority: 10
    services:
    - name: jenkins-server
      port: 8080
      passHostHeader: true
      responseForwarding:
        flushInterval: 100ms
    middlewares:
      - jenkins-server-redirectregex

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: jenkins-server-redirectregex
  namespace: jenkins
spec:
  redirectRegex:
    regex: "^(.*)/login?from=%2Fjenkins$"
    replacement: ${1}/login?from=%2Fjenkins
---