---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: jenkins-server-backend-ingressroute
  namespace: jenkins
spec:
  entryPoints: 
    - web
  routes:
  - kind: Rule
    match: "Path(`/jenkins`)"
    priority: 10
    services:
    - name: jenkins-server
      port: 8080
      passHostHeader: true
      responseForwarding:
        flushInterval: 100ms
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: jenkins-server-frontend-ingressroute
  namespace: jenkins
spec:
  entryPoints: 
    - web
  routes:
  - kind: Rule
    match: "Path(`/login`)"
    priority: 10
    services:
    - name: jenkins-server
      port: 8080
      passHostHeader: true
      responseForwarding:
        flushInterval: 100ms
    middlewares:
    - name: jenkins-server-addprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: jenkins-server-addprefix
spec:
  addPrefix:
    prefix: /jenkins
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced
---