---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: jenkins-server-frontend-ingressroute
  namespace: jenkins
spec:
  entryPoints: 
    - web
  routes:
  - kind: Rule
    match: "PATH(`/jenkins`)"
    priority: 10
    services:
    - name: jenkins-server
      port: 8080
      passHostHeader: true
    middlewares:
    - name: stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: jenkins
spec:
  stripPrefix:
    prefixes:
      - /jenkins
      - /jenkins/
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirectregex
  namespace: jenkins
spec:
  redirectRegex:
    regex: ^(http:\/\/(\[[\w:.]+\]|[\w\._-]+)(:\d+)?)\/$
    replacement: ${1}/jenkins/
---