---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: go-swagger-pvc
  namespace: go-swagger
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
kind: Pod
apiVersion: v1
metadata:
  name: go-swagger
  namespace: go-swagger
spec:
  containers:
  - name: go-swagger
    image: quay.io/goswagger/swagger
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "cat"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
    resources:
      requests:
        memory: 128Mi
        cpu: 250m
      limits:
        memory: 256Mi
        cpu: 500m
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: go-swagger-pvc
---