---
# ConfigMap Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-unifi-controller-telegraf-config
  namespace: unifi-controller
  labels:
    app: unifi-controller-telegraf
data:
  telegraf-unifi-controller.conf: |-
    # Telegraf Configuration

    [agent]
      interval = "10s"
      round_interval = true

    [[outputs.influxdb]]
        urls = ["http://k8snode1dc1.jittersolutions.com:30030"]
        database = "telegraf"
        insecure_skip_verify = true
        #ssl_ca = "/usr/local/etc/telegraf.ca"
    
    ## INPUT CONFIGURATION
    ### Retrieves details via SNMP from UniFI APs (Gen 2 and later)
    ### Extra MIBs required:
    ### - http://dl.ubnt-ut.com/snmp/UBNT-MIB
    ### - http://dl.ubnt-ut.com/snmp/UBNT-UniFi-MIB

    [[inputs.snmp]]
      # List of agents to poll
      agents = [ "apt1dc1" ]
      # Polling interval
      interval = "60s"
      # Timeout for each SNMP query.
      timeout = "10s"
      # Number of retries to attempt within timeout.
      retries = 3
      # SNMP version
      version = 2
      # SNMP community string.
      community = "public"
      # Measurement name
      name = "snmp.UAP"
      ##
      ## System Details
      ##
      #  System name (hostname)
      [[inputs.snmp.field]]
        is_tag = true
        name = "sysName"
        oid = "RFC1213-MIB::sysName.0"
      #  System vendor OID
      [[inputs.snmp.field]]
        name = "sysObjectID"
        oid = "RFC1213-MIB::sysObjectID.0"
      #  System description
      [[inputs.snmp.field]]
        name = "sysDescr"
        oid = "RFC1213-MIB::sysDescr.0"
      #  System contact
      [[inputs.snmp.field]]
        name = "sysContact"
        oid = "RFC1213-MIB::sysContact.0"
      #  System location
      [[inputs.snmp.field]]
        name = "sysLocation"
        oid = "RFC1213-MIB::sysLocation.0"
      #  System uptime
      [[inputs.snmp.field]]
        name = "sysUpTime"
        oid = "RFC1213-MIB::sysUpTime.0"
      #  UAP model
      [[inputs.snmp.field]]
        name = "unifiApSystemModel"
        oid = "UBNT-UniFi-MIB::unifiApSystemModel.0"
      #  UAP firmware version
      [[inputs.snmp.field]]
        name = "unifiApSystemVersion"
        oid = "UBNT-UniFi-MIB::unifiApSystemVersion.0"
      #  Per-interface traffic, errors, drops
      [[inputs.snmp.table]]
        oid = "IF-MIB::ifTable"
        [[inputs.snmp.table.field]]
          is_tag = true
          oid = "IF-MIB::ifDescr"
      ##
      ## Interface Details & Metrics
      ##
      #  Wireless interfaces
      [[inputs.snmp.table]]
        oid = "UBNT-UniFi-MIB::unifiRadioTable"
        [[inputs.snmp.table.field]]
          is_tag = true
          oid = "UBNT-UniFi-MIB::unifiRadioName"
        [[inputs.snmp.table.field]]
          is_tag = true
          oid = "UBNT-UniFi-MIB::unifiRadioRadio"
      #  BSS instances
      [[inputs.snmp.table]]
        oid = "UBNT-UniFi-MIB::unifiVapTable"
        [[inputs.snmp.table.field]]
          is_tag = true
          oid = "UBNT-UniFi-MIB::unifiVapName"
        [[inputs.snmp.table.field]]
          is_tag = true
          oid = "UBNT-UniFi-MIB::unifiVapRadio"
        [[inputs.snmp.table.field]]
          is_tag = true
          oid = "UBNT-UniFi-MIB::unifiVapEssId"
      #  Ethernet interfaces
      [[inputs.snmp.table]]
        oid = "UBNT-UniFi-MIB::unifiIfTable"
        [[inputs.snmp.table.field]]
          is_tag = true
          oid = "UBNT-UniFi-MIB::unifiIfName"
      ##
      ## SNMP metrics
      ##
      #  Number of SNMP messages received
      [[inputs.snmp.field]]
        name = "snmpInPkts"
        oid = "SNMPv2-MIB::snmpInPkts.0"
      #  Number of SNMP Get-Request received
      [[inputs.snmp.field]]
        name = "snmpInGetRequests"
        oid = "SNMPv2-MIB::snmpInGetRequests.0"
      #  Number of SNMP Get-Next received
      [[inputs.snmp.field]]
        name = "snmpInGetNexts"
        oid = "SNMPv2-MIB::snmpInGetNexts.0"
      #  Number of SNMP objects requested
      [[inputs.snmp.field]]
        name = "snmpInTotalReqVars"
        oid = "SNMPv2-MIB::snmpInTotalReqVars.0"
      #  Number of SNMP Get-Response received
      [[inputs.snmp.field]]
        name = "snmpInGetResponses"
        oid = "SNMPv2-MIB::snmpInGetResponses.0"
      #  Number of SNMP messages sent
      [[inputs.snmp.field]]
        name = "snmpOutPkts"
        oid = "SNMPv2-MIB::snmpOutPkts.0"
      #  Number of SNMP Get-Request sent
      [[inputs.snmp.field]]
        name = "snmpOutGetRequests"
        oid = "SNMPv2-MIB::snmpOutGetRequests.0"
      #  Number of SNMP Get-Next sent
      [[inputs.snmp.field]]
        name = "snmpOutGetNexts"
        oid = "SNMPv2-MIB::snmpOutGetNexts.0"
      #  Number of SNMP Get-Response sent
      [[inputs.snmp.field]]
        name = "snmpOutGetResponses"
        oid = "SNMPv2-MIB::snmpOutGetResponses.0"
      #  Processor listing
      [[inputs.snmp.table]]
        index_as_tag = true
        oid = "HOST-RESOURCES-MIB::hrProcessorTable"
      ##
      ## Host performance metrics
      ##
      #  System Load Average
      [[inputs.snmp.table]]
        oid = "UCD-SNMP-MIB::laTable"
        [[inputs.snmp.table.field]]
          oid = "UCD-SNMP-MIB::laNames"
          is_tag = true
      ##
      ## System Memory (physical/virtual)
      ##
      #  Size of swap sapce configured
      [[inputs.snmp.field]]
        name = "memTotalSwap"
        oid = "UCD-SNMP-MIB::memTotalSwap.0"
      #  Size of swap sapce unused/avail
      [[inputs.snmp.field]]
        name = "memAvailSwap"
        oid = "UCD-SNMP-MIB::memAvailSwap.0"
      #  Size of real/phys mem installed
      [[inputs.snmp.field]]
        name = "memTotalReal"
        oid = "UCD-SNMP-MIB::memTotalReal.0"
      #  Size of real/phys mem unused/avail
      [[inputs.snmp.field]]
        name = "memAvailReal"
        oid = "UCD-SNMP-MIB::memAvailReal.0"
      #  Total amount of mem unused/avail
      [[inputs.snmp.field]]
        name = "memTotalFree"
        oid = "UCD-SNMP-MIB::memTotalFree.0"
      #  Size of mem used as shared memory
      [[inputs.snmp.field]]
        name = "memShared"
        oid = "UCD-SNMP-MIB::memShared.0"
      #  Size of mem used for buffers
      [[inputs.snmp.field]]
        name = "memBuffer"
        oid = "UCD-SNMP-MIB::memBuffer.0"
      #  Size of mem used for cache
      [[inputs.snmp.field]]
        name = "memCached"
        oid = "UCD-SNMP-MIB::memCached.0"
      #
---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller-telegraf
  namespace: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller-telegraf
  template:
    metadata:
      labels:
        app: unifi-controller-telegraf
    spec:
      volumes:
      - name: unifi-controller-telegraf-config
        configMap:
          defaultMode: 0600
          name: cm-unifi-controller-telegraf-config
      containers:
      - name: unifi-controller-telegraf
        image: telegraf:alpine
        command: ["/bin/sh", "-c"]
        args: [
          "wget http://dl.ubnt-ut.com/snmp/UBNT-MIB -P /usr/share/snmp/mibs/",
          "wget http://dl.ubnt-ut.com/snmp/UBNT-UniFi-MIB -P /usr/share/snmp/mibs/",
        ]
        volumeMounts:
          - name: unifi-controller-telegraf-config
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf-unifi-controller.conf
            readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
---