---
# PersistentVolumeClaim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-pvc
  namespace: traefik
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  namespace: traefik
  labels:
    app: traefik
data:
---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      volumes:
      - name: traefik-config
        persistentVolumeClaim:
          claimName: traefik-pvc
      containers:
      - name: traefik
        image: traefik:v2.3
        volumeMounts:
          - name: traefik-config
            mountPath: /etc/traefik/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: traefik-configmap
        ports:
        - containerPort: 8080
---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32280
  selector:
    app: traefik
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---