---
# PersistentVolumeClaim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-server-config
  namespace: plex
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
# ConfigMap Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-server-env
  namespace: plex
  labels:
    app: plex-server
data:
  PUID: 1000
  PGID: 1000
  VERSION: docker
---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: plex-server
  namespace: plex
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 32400
    name: port0
    protocol: TCP
    targetPort: 32400
    nodePort: 32400
  selector:
    app: plex-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-server
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-server
  template:
    metadata:
      labels:
        app: plex-server
    spec:
      serviceAccountName: plex
      volumes:
      - name: plex-server-config
        persistentVolumeClaim:
          claimName: pvc-plex-server-config
      containers:
      - name: plex-server
        image: linuxserver/plex
        volumeMounts:
          - name: plex-server-config
            mountPath: /config
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        envFrom:
          - configMapRef:
              name: plex-server-env
        ports:
        - containerPort: 32400 #Plex Media Server
          name: port0
---