---
# Namespace Configuration
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
# Issuer Configuration
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: cloudflare-issuer
  namespace: cert-manager-test
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: freemanz2@outlook.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: example-issuer-account-key
    # Add a single challenge solver, dns01 using cloudflare
    solvers:
    - dns01:
        cloudflare:
          email: freemanz2@outlook.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
# Certificate Configuration
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: letsencrypt-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - jittersolutions.com
  secretName: letsencrypt-cert-tls
  issuerRef:
    name: cloudflare-issuer
---