---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
  namespace: gitlab-ce
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab-runner
  template:
    metadata:
      labels:
        name: gitlab-runner
    spec:
      serviceAccountName: gitlab
      containers:
        - name: gitlab-runner
          image: gitlab/gitlab-runner:latest
          command: ["/bin/sh", "-c"]
          args: [
            "gitlab-register",
            "--config /tmp/test-config.toml",
            "--non-interactive",
            "--url https://gitlab.com",
            "--registration-token tR7ou1ymGKVVJodS4xEG",
            "--name $hostname",
            "--executor kubernetes"
          ]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
      restartPolicy: Always
---