---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: vault-server
  namespace: vault
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8200
    name: http
    protocol: TCP
    targetPort: 8200
    nodePort: 32385
  selector:
    app: vault-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-server
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-server
  template:
    metadata:
      labels:
        app: vault-server
    spec:
      containers:
      - name: vault-server
        image: vault:1.5.5
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
        ports:
        - containerPort: 8200
          name: http
        #securityContext:
        #  runAsUser: 0
---