---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-deploy-1
  labels:
    type: nfs
spec:
  storageClassName: nfs-k8s-storage
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.110.245
    path: "/mnt/pool2/k8s_storage/nginx-deploy"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-deploy-1
spec:
  storageClassName: nfs-k8s-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-nginx-deploy-1
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy
  namespace: nginx
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---