---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: teamcity-server-ingressroute
  namespace: teamcity
spec:
  entryPoints: 
    - web
  routes:
  - kind: Rule
    match: "(Host(`k8snode2dc1.jittersolutions.com`) && Path(`/teamcity`))" 
    priority: 10
    services:
    - name: teamcity-server
      namespace: teamcity
      port: 8111
      path: "/"
---