---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: teamcity-server-ingressroute
  namespace: teamcity
spec:
  entryPoints: 
    - web
  routes:
  - kind: Rule
    match: "Path(`/teamcity`)" 
    priority: 10
    services:
    - name: teamcity-server
      namespace: teamcity
      port: 8111
---